### ISSUE TITLE
フォルダのアップロードについて

### ISSUE THREAD

**Issue by Myoko1110** [Necnion8/CraftSwitcher-2#26]
フォルダのアップロードに関する件です。

現在、ファイルのアップロードは、ファイルデータの保存用APIを活用し、ファイルを個別にアップロードする形をとっています。
しかしそのため、フォルダのアップロードをすると、フォルダ単位でのアップロードができず、フォルダの中身のファイルのみのアップロードしかできません。

例えば、
次のフォルダを/mainにアップロードするとします。
```
plugins
 ├ A.jar
 └ B.jar
```
しかし、ファイル単位でのアップロードのため以下のようになってしまいます。
```
/main
 ├ A.jar
 └ B.jar
 ```
 実現したいものは以下のようなものです。
 ```
/main
 ├ plugins/
 |  ├ A.jar
 |  └ B.jar
 ```

そこで、ファイルをアップロードするためのAPIを作っていただけると幸いです。
最終的には複数フォルダのアップロードにも対応させたいなと思っています。

**Comment by Necnion8** [comment]
mkdir で事前に必要な階層(フォルダ)を作成してからファイルをアップロードすることで、ディレクトリの構造を残したままファイルを配置できそうですがどうでしょうか？

**Comment by Necnion8** [comment]
一括でディレクトリツリーを作成できるように mkdir に変更 e7188725 を加えてみました。

**Comment by Myoko1110** [comment]
試してみます。

**Comment by Myoko1110** [comment]
処理が煩雑になってしまいましたが、とりあえず実装してみました。
https://github.com/Myoko1110/CraftSwitcher2-Client/commit/a731fb3c74e4a5dd7c685fb5ecc7572c7e94c7fe
https://github.com/Myoko1110/CraftSwitcher2-Client/commit/61fd669c141a94551598c7fd698459fa6a8917c0

**Comment by Necnion8** [comment]
いいと思いますが、どうですか？
処理コストが大きいだったり何か都合が悪い点があればサーバーで実装することも検討します。

**Comment by Myoko1110** [comment]
比較的多くのファイルをアップロードしようとすると、大量にリクエストが送られてしまうので、よくない気がしますが…
とりあえずこれで良いことにします。

**Comment by Necnion8** [comment]
確かに･･･。
大量のファイルを直接アップロードするとは全く想定していなかったですね...私。
