### ISSUE TITLE
ターミナルサイズについて

### ISSUE THREAD

**Issue by Myoko1110** [Necnion8/CraftSwitcher-2#30]
Spigot系サーバーのターミナルでコマンドを手入力する際、まだ正しくないコマンドが赤い文字で表示されていて、正しいコマンドを完全に入力し終えると、白い文字に変わると思います。

このときのANSIコードを見ると、その行の最初に行くという処理が書かれていますが、その行を指定する際に、バックエンドとフロントエンドのターミナルサイズが違うため、違う場所へ入力が行ってしまうことがあります。
（わかりにくくてごめんなさい）

フロントエンド側で、行番号をいじるという方法も考えたのですが、ANSIコードをいじるのはあまり良くない気がしました。

そのため、ターミナルサイズを指定する機能を作成してくれると幸いです。（WSで実装してくれると嬉しいです）

**Comment by Necnion8** [comment]
サーバープロセスの読み書きに擬似端末(pty)を使う仕組みをとっていますが、これを扱うライブラリがUnix系とWindowsで違うものを使っています。
Windowsで使われるライブラリではターミナルサイズを設定することができるんですが、Unix系で使っているものにそのようなAPIが見当たらず。(ターミナルサイズという概念がない？)

もしかしたら端末制御コードにサイズを設定する命令があるのでしょうか･･･。現状、まだ詳しく調査できていません。

**Comment by Myoko1110** [comment]
そうなんですね…
Unix系でどういう挙動になるのか少し試してみます。
もしできなさそうであれば、フロントエンド側で対処できるように頑張ります

（調査お願いします…！）

**Comment by Necnion8** [comment]
GNU Screen を使う場合でもまた挙動がおかしくなる時があるので、可能な限りバックエンドで対策できるようにしておきたいと思っています。

もしそちらでも何かわかったことがあればぜひお知らせをください･･･！

**Comment by Necnion8** [comment]
Myokoさんの説明にある通り、バックエンドとフロントエンドのターミナルサイズを同じにすることで、入力中にカーソルが飛ばなくなることを確認しました。<br>

まだ仮の別ブランチ上ですが WS の方に `server_process_set_term_size` というのを追加して、サイズを設定できるようにしてみました。
https://github.com/Necnion8/CraftSwitcher-2/blob/befaee146ea1ac79ec4cabe77b922419f7ec282e/dncore/extensions/craftswitcher/publicapi/handler.py#L151-L175

Unixでもサイズ変更できるものが見つかったので、そちらの実装に切り替えて試行錯誤しています。

https://github.com/Necnion8/CraftSwitcher-2/tree/dev/fix-termsize-ptyprocess
https://github.com/Necnion8/CraftSwitcher-2/tree/dev/fix-termsize-fcntl

**Comment by Myoko1110** [comment]
ありがとうございます！！

**Comment by Necnion8** [comment]
Unix用のptyライブラリを使わず
元々の実装のままシステムコールを使いリサイズに対応できたのでそちらで進めます。
https://github.com/Necnion8/CraftSwitcher-2/tree/dev/fix-termsize-fcntl

このまま問題がなさそうであればマージしたいと思います

**Comment by Necnion8** [comment]
マージしたので閉じます👍
